apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  containers:
  - image: bmuschko/nodejs-read-config:1.0.0
    name: web
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: workdir
      mountPath: /usr/shared/app
  initContainers:
  - name: configurer
    image: busybox:1.28
    command: ['sh', '-c', "wget https://raw.githubusercontent.com/bmuschko/ckad-crash-course/master/exercises/03-init-container/app/config/config.json -O /usr/shared/app/config.json"]
    volumeMounts:
    - name: workdir
      mountPath: /usr/shared/app
  dnsPolicy: ClusterFirst
  volumes:
  - name: workdir
    emptyDir: {}
  restartPolicy: Always
status: {}
